repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args:
          - --line-length=80
    -   id: black-jupyter
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.0
  hooks:
    - id: mypy
      exclude: ^tests/
      args:
      - --disallow-untyped-defs
      - --disallow-incomplete-defs
      - --disallow-untyped-calls
      - --ignore-missing-imports
      additional_dependencies:
      - types-pyyaml
      - types-requests
      - pandas-stubs
