name: house-price-model-env
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pre-commit
  - pyyaml
  - types-pyyaml
  - jupyter
  - pytest
  - requests
  - types-requests
  - pandas
  - flake8
  - pip
  - pip:
      - pyjstat
