name: house-price-model-env
channels:
  - conda-forge
dependencies:
  - python==3.10.9
  - pre-commit==3.4.0
  - pyyaml==6.0.1
  - jupyter==1.0.0
  - jinja2==3.0.3
  - nbconvert==6.4.4
  - pytest==7.4.1
  - requests==2.31.0
  - pandas==2.0.0
  - flake8==6.0.0
  - pip==23.2.1
  - statsmodels==0.14.0
  - matplotlib==3.7.1
  - scikit-learn=1.2.2
  - flask==2.0.3
  - gunicorn==20.1.0
  - pip:
      - pyjstat==2.4.0
variables:
  FLASK_APP: app/run.py
  FLASK_DEBUG: true
