name: house-price-model-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter=1.0.0
  - plotly=5.13.0
  - polars=0.15.14
  - pre-commit=3.0.4
  - pyyaml=6.0
  - types-pyyaml=6.0.12.5
