app:
  data_path: 'app/data/model_data.json'

model:
  horizon: 8  # Number of quarters into the future the model is applicable
  class: auto_regression
  kwargs:
    lags: [1, 3, 4]
    seasonal: true

data_loading:
  ssb_api_url: 'https://data.ssb.no/api/v0/no/table/'

  house_prices:
    table: '07240'
    query:
      - key: Boligtype
        filter: 'item'
        values: ['00']
      - key: ContentsCode
        filter: 'item'
        values: ['KvPris']
